harnessApiVersion: '1.0'
type: APPLICATION_MANIFEST
gitFileConfig:
  branch: master
  connectorName: accout
  repoName: PipelinesNgAutomation
  useBranch: true
  useInlineServiceDefinition: false
kustomizeConfig:
  kustomizeDirPath: CGKustomizePatches/PatchesTest/kustomize-plugin/hello-world/
  pluginRootDir: /opt/harness-delegate/
skipVersioningForAllK8sObjects: true
storeType: KustomizeSourceRepo
